services:
  php-fpm:
    build:
      context: .
    ports:
     - 9000:9000
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    links:
      - database
  nginx:
    image: nginx:alpine
    ports:
      - 90:80
      - 443:443
    volumes:
      - ./:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    working_dir: /var/www/
    links:
      - database

  composer:
    image: composer
    command: ['install', '--ignore-platform-reqs']
    volumes:
      - ./:/var/www/
    working_dir: /var/www/

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    
# Names our volume
volumes:
  my-db: