<?php
$title = 'Cadastrar empresa';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$empresa = $form->get('razao_social');
$empresa->setAttribute('class', 'form-control');
$empresa->setAttribute('placeholder', 'Nome da empresa');

$cnpj = $form->get('cnpj');
$cnpj->setAttribute('class', 'form-control');
$cnpj->setAttribute('id', 'cnpj');
$cnpj->setAttribute('placeholder', 'CNPJ');

$cep = $form->get('cep');
$cep->setAttribute('class', 'form-control');
$cep->setAttribute('id', 'cep');
$cep->setAttribute('placeholder', 'CEP');

$cidade = $form->get('cidade');
$cidade->setAttribute('class', 'form-control');
$cidade->setAttribute('placeholder', 'Cidade');

$estado = $form->get('estado');
$estado->setAttribute('class', 'form-control');

$bairro = $form->get('bairro');
$bairro->setAttribute('class', 'form-control');
$bairro->setAttribute('placeholder', 'Bairro');

$complemento = $form->get('complemento');
$complemento->setAttribute('class', 'form-control');
$complemento->setAttribute('placeholder', 'Complemento');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('empresa', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($empresa) ?>
    <?= $this->formElement($empresa) ?>
    <?= $this->formElementErrors()->render($empresa, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($cnpj) ?>
    <?= $this->formElement($cnpj) ?>
    <?= $this->formElementErrors()->render($cnpj, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($cep) ?>
    <?= $this->formElement($cep) ?>
    <?= $this->formElementErrors()->render($cep, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($estado) ?>
    <?= $this->formElement($estado) ?>
    <?= $this->formElementErrors()->render($estado, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($cidade) ?>
    <?= $this->formElement($cidade) ?>
    <?= $this->formElementErrors()->render($cidade, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($bairro) ?>
    <?= $this->formElement($bairro) ?>
    <?= $this->formElementErrors()->render($bairro, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($complemento) ?>
    <?= $this->formElement($complemento) ?>
    <?= $this->formElementErrors()->render($complemento, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();


$this->headScript()->prependFile(
    '/js/jquery-3.5.1.min.js',
    'text/javascript',
);


$this->headScript()->appendFile(
    '/js/empresa.js',
    'text/javascript',
);
$this->headScript();
?>
<script src='/js/jquery.mask.min.js'/>