<?php
// module/Empresa/view/empresa/empresa/delete.phtml:

$title = 'Remover empresa';
$url   = $this->url('empresa', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Tem certeza que deseja excluir a empresa
    <?= $this->escapeHtml($empresa->razao_social) ?>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $empresa->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>