<?php
// module/Empresa/view/empresa/empresa/edit.phtml:
use Carbon\Carbon;
$title = 'Editar licença';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$numero = $form->get('numero');
$numero->setAttribute('class', 'form-control');
$numero->setAttribute('placeholder', 'Empresa title');
$numero->setAttribute('disabled', true);

$orgao_ambiental = $form->get('orgao_ambiental');
$orgao_ambiental->setAttribute('class', 'form-control');
$orgao_ambiental->setAttribute('placeholder', 'Orgão');

$empresa_id = $form->get('empresa_id');
$empresa_id->setAttribute('class', 'form-control');

$validade = $form->get('validade');
$validade->setAttribute('class', 'form-control');
$validade->setAttribute('min', Carbon::now()->add('1 day')->format('Y-m-d'));

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');


$form->setAttribute('action', $this->url('licenca', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($numero) ?>
    <?= $this->formElement($numero) ?>
    <?= $this->formElementErrors()->render($numero, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($orgao_ambiental) ?>
    <?= $this->formElement($orgao_ambiental) ?>
    <?= $this->formElementErrors()->render($orgao_ambiental, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($empresa_id) ?>
    <?= $this->formElement($empresa_id) ?>
    <?= $this->formElementErrors()->render($empresa_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($validade) ?>
    <?= $this->formElement($validade) ?>
    <?= $this->formElementErrors()->render($validade, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();