<head>

</head>
<?php
$title = 'Licencas';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('licenca', ['action' => 'add']) ?>">Cadastrar licenca</a>
</p>

<table class="table">
<tr>
    <th>Numero</th>
    <th>Orgão</th>
    <th>Emissão</th>
    <th>Valido até</th>
    <th>Empresa</th>
    <th>&nbsp;</th>
</tr>
<?php if(count($licencas) <= 0):?>
        <tr><td> <span>Não há licenças cadastradas</span> </td></tr>
<?php endif?>
<?php foreach ($licencas as $licenca) : ?>
    
    <tr>
        <td><?= $this->escapeHtml($licenca->numero) ?></td>
        <td><?= $this->escapeHtml($licenca->orgao_ambiental) ?></td>
        <td id='emissao'><?= $this->escapeHtml($licenca->emissao) ?></td>
        <td><?= $this->escapeHtml($licenca->validade) ?></td>
        <td><?= $this->escapeHtml($licenca->empresa->razao_social ?? "N/A") ?></td>
        <td>
            <a href="<?= $this->url('licenca', ['action' => 'edit', 'id' => $licenca->id]) ?>">Editar</a>
            <a href="<?= $this->url('licenca', ['action' => 'delete', 'id' => $licenca->id]) ?>">Remover</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php 
$this->headScript()->prependFile(
    '/js/jquery-3.5.1.min.js',
    'text/javascript',
);

$this->headScript()->appendFile(
    '/js/licenca.js',
    'text/javascript',
);?>
<script src='/js/jquery.mask.min.js'/>

